package incident;

public enum IncidentEntryType {
	CREATE, DETECTION, REPORTING, INFORMATION_COLLECTION, ASSESSMENT_1, ASSESSMENT_2, 
	IMMEDIATE_RESPONSE, LATE_RESPONSE, FORENSIC_ANALYSIS, COMMUNICATIONS, REVIEW;
}
